apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  ports:
    - name: nfs
      port: 2049 #서비스의 IP에 접근할 때 사용할 포트
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector: #어떤 라벨을 가지는 포드에 접근할 수 있게 만들 것인지를 결정
    role: nfs-server
